POST http://localhost:3000/cryptoStat/bitfinex
Content-Type: application/json

###

POST http://localhost:3000/cryptoStat/kraken
Content-Type: application/json

###

GET http://localhost:3000/crypto

###